FROM busybox:1.28
WORKDIR /root/
ENV MEDICHAIN_PATH=/root
COPY ca-certificates.crt /etc/ssl/certs/
COPY etc/config.json ./etc/
COPY sql/tbl_file_add_event_log.sql ./sql/
COPY main .
EXPOSE 8443/tcp
ENTRYPOINT ["./main"]