kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ${MEDICHAIN_NAME}-ceph-pvc-keystore
  namespace: ${MEDICHAIN_NAMESPACE}
spec:
  selector:
    matchLabels:
      pv: ${MEDICHAIN_NAME}-ceph-pv
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: ${MEDICHAIN_CEPH_PVC_KEYSTORE_SIZE}