apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${MEDICHAIN_NAME}-deploy
  namespace: ${MEDICHAIN_NAMESPACE}
  labels:
    app: ${MEDICHAIN_NAME}-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${MEDICHAIN_NAME}-deploy
  template:
    metadata:
      labels:
        app: ${MEDICHAIN_NAME}-deploy
    spec:
      containers:
      - name: medichain
        image: ${MEDICHAIN_IMAGE}
        imagePullPolicy: Always
        ports:
        - containerPort: ${MEDICHAIN_PORT}
          protocol: TCP
        volumeMounts:
        - name: ${MEDICHAIN_NAME}-config-volume
          mountPath: /root/etc # 这里是路径
        - name: ${MEDICHAIN_NAME}-keystore-volume
          mountPath: /root/keystore # 这里是容器目录
          subPath: data/blockchain/medichain/keystore # 这里是ceph卷里面的目录
        - name: ${MEDICHAIN_NAME}-databases-volume
          mountPath: /root/databases
          subPath: data/blockchain/medichain/databases
      volumes:
      - name: ${MEDICHAIN_NAME}-databases-volume
        persistentVolumeClaim:
          claimName: ${MEDICHAIN_NAME}-ceph-pvc-databases
      - name: ${MEDICHAIN_NAME}-keystore-volume
        persistentVolumeClaim:
          claimName: ${MEDICHAIN_NAME}-ceph-pvc-keystore
      - name: ${MEDICHAIN_NAME}-config-volume
        configMap:
          name: ${MEDICHAIN_NAME}-configmap
          items:
          - key: first # 使用configmap里面key对应的数据
            path: config.json # 代表/root/etc/config.json文件
      restartPolicy: Always

