kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ${MEDICHAIN_NAME}-ceph-pvc-databases
  namespace: ${MEDICHAIN_NAMESPACE}
spec:
  selector:
    matchLabels:
      pv: ${MEDICHAIN_NAME}-ceph-pv-databases
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: ${MEDICHAIN_CEPH_PVC_DATABASES_SIZE}
